// Action-Types
// ============
const cartActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  DECREASE_CART_ITEM_COUNT: "DECREASE_CART_ITEM_COUNT",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  SET_CART_ITEM_FROM_STORAGE: "SET_CART_ITEM_FROM_STORAGE"
};

export default cartActionTypes;
