const SHOP_DATA = { men:
   [ { id: 'men-shoes',
       title: 'Shoes',
       items:
        [ { id: 1,
            name: 'Denim organza shoe',
            imageURL: 'https://picsum.photos/id/1/200/300',
            price: 421 },
          { id: 2,
            name: 'Dungarees yarn shoe',
            imageURL: 'https://picsum.photos/id/2/200/300',
            price: 560 },
          { id: 3,
            name: 'Denim tweed shoe',
            imageURL: 'https://picsum.photos/id/3/200/300',
            price: 464 },
          { id: 4,
            name: 'Dungarees lace shoe',
            imageURL: 'https://picsum.photos/id/4/200/300',
            price: 468 },
          { id: 5,
            name: 'Wool sateen shoe',
            imageURL: 'https://picsum.photos/id/5/200/300',
            price: 543 },
          { id: 6,
            name: 'Fabric surface shoe',
            imageURL: 'https://picsum.photos/id/6/200/300',
            price: 485 },
          { id: 7,
            name: 'Baft yarn shoe',
            imageURL: 'https://picsum.photos/id/7/200/300',
            price: 491 },
          { id: 8,
            name: 'Wool glossy shoe',
            imageURL: 'https://picsum.photos/id/8/200/300',
            price: 582 },
          { id: 9,
            name: 'blue nylon shoe',
            imageURL: 'https://picsum.photos/id/9/200/300',
            price: 507 },
          { id: 10,
            name: 'Cotton chiffon shoe',
            imageURL: 'https://picsum.photos/id/10/200/300',
            price: 435 } ] },
     { id: 'men-socks',
       title: 'Socks',
       items:
        [ { id: 11,
            name: 'Dungarees venise sock',
            imageURL: 'https://picsum.photos/id/11/200/300',
            price: 534 },
          { id: 12,
            name: 'Dungarees nylon sock',
            imageURL: 'https://picsum.photos/id/12/200/300',
            price: 511 },
          { id: 13,
            name: 'Corduroy chiffon sock',
            imageURL: 'https://picsum.photos/id/13/200/300',
            price: 568 },
          { id: 14,
            name: 'Gabardine short sock',
            imageURL: 'https://picsum.photos/id/14/200/300',
            price: 446 },
          { id: 15,
            name: 'Flannel lace sock',
            imageURL: 'https://picsum.photos/id/15/200/300',
            price: 435 },
          { id: 16,
            name: 'Cotton chiffon sock',
            imageURL: 'https://picsum.photos/id/16/200/300',
            price: 439 },
          { id: 17,
            name: 'Satin rubber sock',
            imageURL: 'https://picsum.photos/id/17/200/300',
            price: 492 },
          { id: 18,
            name: 'Damask yarn sock',
            imageURL: 'https://picsum.photos/id/18/200/300',
            price: 495 },
          { id: 19,
            name: 'Wool yarn sock',
            imageURL: 'https://picsum.photos/id/19/200/300',
            price: 402 },
          { id: 20,
            name: 'Fabric mohair sock',
            imageURL: 'https://picsum.photos/id/20/200/300',
            price: 424 } ] },
     { id: 'men-jeans',
       title: 'Jeans',
       items:
        [ { id: 21,
            name: 'Crinoline mohair jean',
            imageURL: 'https://picsum.photos/id/21/200/300',
            price: 486 },
          { id: 22,
            name: 'Corduroy yarn jean',
            imageURL: 'https://picsum.photos/id/22/200/300',
            price: 421 },
          { id: 23,
            name: 'Dungarees surface jean',
            imageURL: 'https://picsum.photos/id/23/200/300',
            price: 498 },
          { id: 24,
            name: 'Crinoline nylon jean',
            imageURL: 'https://picsum.photos/id/24/200/300',
            price: 541 },
          { id: 25,
            name: 'Gabardine nylon jean',
            imageURL: 'https://picsum.photos/id/25/200/300',
            price: 590 },
          { id: 26,
            name: 'Batiste fleck jean',
            imageURL: 'https://picsum.photos/id/26/200/300',
            price: 415 },
          { id: 27,
            name: 'Batiste velvet jean',
            imageURL: 'https://picsum.photos/id/27/200/300',
            price: 514 },
          { id: 28,
            name: 'Angora surface jean',
            imageURL: 'https://picsum.photos/id/28/200/300',
            price: 534 },
          { id: 29,
            name: 'Flannel lace jean',
            imageURL: 'https://picsum.photos/id/29/200/300',
            price: 557 },
          { id: 30,
            name: 'Baldachin yarn jean',
            imageURL: 'https://picsum.photos/id/30/200/300',
            price: 479 } ] },
     { id: 'men-trousers',
       title: 'trousers',
       items:
        [ { id: 31,
            name: 'Thread velvet trouser',
            imageURL: 'https://picsum.photos/id/31/200/300',
            price: 403 },
          { id: 32,
            name: 'Dungarees surface trouser',
            imageURL: 'https://picsum.photos/id/32/200/300',
            price: 495 },
          { id: 33,
            name: 'Angora glossy trouser',
            imageURL: 'https://picsum.photos/id/33/200/300',
            price: 434 },
          { id: 34,
            name: 'Satin chiffon trouser',
            imageURL: 'https://picsum.photos/id/34/200/300',
            price: 547 },
          { id: 35,
            name: 'Satin nylon trouser',
            imageURL: 'https://picsum.photos/id/35/200/300',
            price: 543 },
          { id: 36,
            name: 'Angora chiffon trouser',
            imageURL: 'https://picsum.photos/id/36/200/300',
            price: 423 },
          { id: 37,
            name: 'Angora yarn trouser',
            imageURL: 'https://picsum.photos/id/37/200/300',
            price: 504 },
          { id: 38,
            name: 'Milled velvet trouser',
            imageURL: 'https://picsum.photos/id/38/200/300',
            price: 479 },
          { id: 39,
            name: 'Damask lace trouser',
            imageURL: 'https://picsum.photos/id/39/200/300',
            price: 420 },
          { id: 40,
            name: 'Milled moleskin trouser',
            imageURL: 'https://picsum.photos/id/40/200/300',
            price: 526 } ] },
     { id: 'men-jackets',
       title: 'Jackets',
       items:
        [ { id: 41,
            name: 'Batiste yarn jacket',
            imageURL: 'https://picsum.photos/id/41/200/300',
            price: 566 },
          { id: 42,
            name: 'Thread yarn jacket',
            imageURL: 'https://picsum.photos/id/42/200/300',
            price: 488 },
          { id: 43,
            name: 'Thread glossy jacket',
            imageURL: 'https://picsum.photos/id/43/200/300',
            price: 554 },
          { id: 44,
            name: 'Baldachin glossy jacket',
            imageURL: 'https://picsum.photos/id/44/200/300',
            price: 543 },
          { id: 45,
            name: 'Corduroy nylon jacket',
            imageURL: 'https://picsum.photos/id/45/200/300',
            price: 471 },
          { id: 46,
            name: 'Damask fleck jacket',
            imageURL: 'https://picsum.photos/id/46/200/300',
            price: 543 },
          { id: 47,
            name: 'Dungarees venise jacket',
            imageURL: 'https://picsum.photos/id/47/200/300',
            price: 436 },
          { id: 48,
            name: 'Satin tweed jacket',
            imageURL: 'https://picsum.photos/id/48/200/300',
            price: 470 },
          { id: 49,
            name: 'Angora organza jacket',
            imageURL: 'https://picsum.photos/id/49/200/300',
            price: 420 },
          { id: 50,
            name: 'Dungarees venise jacket',
            imageURL: 'https://picsum.photos/id/50/200/300',
            price: 464 } ] },
     { id: 'men-hats',
       title: 'Hats',
       items:
        [ { id: 51,
            name: 'Baft venise hat',
            imageURL: 'https://picsum.photos/id/51/200/300',
            price: 549 },
          { id: 52,
            name: 'Baldachin glossy hat',
            imageURL: 'https://picsum.photos/id/52/200/300',
            price: 403 },
          { id: 53,
            name: 'Batiste venise hat',
            imageURL: 'https://picsum.photos/id/53/200/300',
            price: 527 },
          { id: 54,
            name: 'Wool nylon hat',
            imageURL: 'https://picsum.photos/id/54/200/300',
            price: 441 },
          { id: 55,
            name: 'Linen weave hat',
            imageURL: 'https://picsum.photos/id/55/200/300',
            price: 529 },
          { id: 56,
            name: 'Dungarees loom hat',
            imageURL: 'https://picsum.photos/id/56/200/300',
            price: 570 },
          { id: 57,
            name: 'Corduroy yarn hat',
            imageURL: 'https://picsum.photos/id/57/200/300',
            price: 554 },
          { id: 58,
            name: 'Baft yarn hat',
            imageURL: 'https://picsum.photos/id/58/200/300',
            price: 410 },
          { id: 59,
            name: 'Batiste mohair hat',
            imageURL: 'https://picsum.photos/id/59/200/300',
            price: 487 },
          { id: 60,
            name: 'Baldachin rubber hat',
            imageURL: 'https://picsum.photos/id/60/200/300',
            price: 526 } ] },
     { id: 'men-shirt',
       title: 'Shirt',
       items:
        [ { id: 61,
            name: 'Milled jacquard shirt',
            imageURL: 'https://picsum.photos/id/61/200/300',
            price: 591 },
          { id: 62,
            name: 'Denim organza shirt',
            imageURL: 'https://picsum.photos/id/62/200/300',
            price: 431 },
          { id: 63,
            name: 'Denim stiff shirt',
            imageURL: 'https://picsum.photos/id/63/200/300',
            price: 571 },
          { id: 64,
            name: 'Angora organza shirt',
            imageURL: 'https://picsum.photos/id/64/200/300',
            price: 476 },
          { id: 65,
            name: 'blue surface shirt',
            imageURL: 'https://picsum.photos/id/65/200/300',
            price: 431 },
          { id: 66,
            name: 'Pattern organza shirt',
            imageURL: 'https://picsum.photos/id/66/200/300',
            price: 423 },
          { id: 67,
            name: 'Angora rubber shirt',
            imageURL: 'https://picsum.photos/id/67/200/300',
            price: 572 },
          { id: 68,
            name: 'Thread moleskin shirt',
            imageURL: 'https://picsum.photos/id/68/200/300',
            price: 588 },
          { id: 69,
            name: 'Thread tweed shirt',
            imageURL: 'https://picsum.photos/id/69/200/300',
            price: 471 },
          { id: 70,
            name: 'Dungarees venise shirt',
            imageURL: 'https://picsum.photos/id/70/200/300',
            price: 489 } ] },
     { id: 'men-tshirt',
       title: 'T-shirt',
       items:
        [ { id: 71,
            name: 'Wool nylon t-shirt',
            imageURL: 'https://picsum.photos/id/71/200/300',
            price: 549 },
          { id: 72,
            name: 'Gabardine tweed t-shirt',
            imageURL: 'https://picsum.photos/id/72/200/300',
            price: 489 },
          { id: 73,
            name: 'Dungarees chiffon t-shirt',
            imageURL: 'https://picsum.photos/id/73/200/300',
            price: 493 },
          { id: 74,
            name: 'Wool chiffon t-shirt',
            imageURL: 'https://picsum.photos/id/74/200/300',
            price: 559 },
          { id: 75,
            name: 'Dungarees tweed t-shirt',
            imageURL: 'https://picsum.photos/id/75/200/300',
            price: 468 },
          { id: 76,
            name: 'Linen lace t-shirt',
            imageURL: 'https://picsum.photos/id/76/200/300',
            price: 435 },
          { id: 77,
            name: 'Milled surface t-shirt',
            imageURL: 'https://picsum.photos/id/77/200/300',
            price: 549 },
          { id: 78,
            name: 'Dungarees fleck t-shirt',
            imageURL: 'https://picsum.photos/id/78/200/300',
            price: 430 },
          { id: 79,
            name: 'Pattern stiff t-shirt',
            imageURL: 'https://picsum.photos/id/79/200/300',
            price: 575 },
          { id: 80,
            name: 'Milled loom t-shirt',
            imageURL: 'https://picsum.photos/id/80/200/300',
            price: 573 } ] },
     { id: 'men-watches',
       title: 'watches',
       items:
        [ { id: 81,
            name: 'Fabric glossy watch',
            imageURL: 'https://picsum.photos/id/81/200/300',
            price: 467 },
          { id: 82,
            name: 'Damask tweed watch',
            imageURL: 'https://picsum.photos/id/82/200/300',
            price: 421 },
          { id: 83,
            name: 'Flannel rubber watch',
            imageURL: 'https://picsum.photos/id/83/200/300',
            price: 560 },
          { id: 84,
            name: 'Corduroy organza watch',
            imageURL: 'https://picsum.photos/id/84/200/300',
            price: 484 },
          { id: 85,
            name: 'Linen nylon watch',
            imageURL: 'https://picsum.photos/id/85/200/300',
            price: 518 },
          { id: 86,
            name: 'Pattern loom watch',
            imageURL: 'https://picsum.photos/id/86/200/300',
            price: 489 },
          { id: 87,
            name: 'blue chiffon watch',
            imageURL: 'https://picsum.photos/id/87/200/300',
            price: 535 },
          { id: 88,
            name: 'Baft loom watch',
            imageURL: 'https://picsum.photos/id/88/200/300',
            price: 408 },
          { id: 89,
            name: 'Milled weave watch',
            imageURL: 'https://picsum.photos/id/89/200/300',
            price: 500 },
          { id: 90,
            name: 'Satin jacquard watch',
            imageURL: 'https://picsum.photos/id/90/200/300',
            price: 577 } ] } ],
  women:
   [ { id: 'women-shoes',
       title: 'Shoes',
       items:
        [ { id: 91,
            name: 'Baldachin nylon shoe',
            imageURL: 'https://picsum.photos/id/91/200/300',
            price: 466 },
          { id: 92,
            name: 'Fabric jacquard shoe',
            imageURL: 'https://picsum.photos/id/92/200/300',
            price: 578 },
          { id: 93,
            name: 'Pattern rubber shoe',
            imageURL: 'https://picsum.photos/id/93/200/300',
            price: 457 },
          { id: 94,
            name: 'Cotton weave shoe',
            imageURL: 'https://picsum.photos/id/94/200/300',
            price: 562 },
          { id: 95,
            name: 'Thread tweed shoe',
            imageURL: 'https://picsum.photos/id/95/200/300',
            price: 525 },
          { id: 96,
            name: 'Milled velvet shoe',
            imageURL: 'https://picsum.photos/id/96/200/300',
            price: 501 },
          { id: 97,
            name: 'Denim lace shoe',
            imageURL: 'https://picsum.photos/id/97/200/300',
            price: 484 },
          { id: 98,
            name: 'Pattern weave shoe',
            imageURL: 'https://picsum.photos/id/98/200/300',
            price: 405 },
          { id: 99,
            name: 'Gabardine stiff shoe',
            imageURL: 'https://picsum.photos/id/99/200/300',
            price: 545 },
          { id: 100,
            name: 'Gabardine fleck shoe',
            imageURL: 'https://picsum.photos/id/100/200/300',
            price: 548 } ] },
     { id: 'women-socks',
       title: 'Socks',
       items:
        [ { id: 101,
            name: 'Thread lace sock',
            imageURL: 'https://picsum.photos/id/101/200/300',
            price: 575 },
          { id: 102,
            name: 'Milled tweed sock',
            imageURL: 'https://picsum.photos/id/102/200/300',
            price: 404 },
          { id: 103,
            name: 'Baft weave sock',
            imageURL: 'https://picsum.photos/id/103/200/300',
            price: 597 },
          { id: 104,
            name: 'Pattern fleck sock',
            imageURL: 'https://picsum.photos/id/104/200/300',
            price: 424 },
          { id: 105,
            name: 'Flannel weave sock',
            imageURL: 'https://picsum.photos/id/105/200/300',
            price: 555 },
          { id: 106,
            name: 'Denim glossy sock',
            imageURL: 'https://picsum.photos/id/106/200/300',
            price: 486 },
          { id: 107,
            name: 'Flannel chiffon sock',
            imageURL: 'https://picsum.photos/id/107/200/300',
            price: 502 },
          { id: 108,
            name: 'Batiste weave sock',
            imageURL: 'https://picsum.photos/id/108/200/300',
            price: 547 },
          { id: 109,
            name: 'Flannel rubber sock',
            imageURL: 'https://picsum.photos/id/109/200/300',
            price: 484 },
          { id: 110,
            name: 'Milled chiffon sock',
            imageURL: 'https://picsum.photos/id/110/200/300',
            price: 536 } ] },
     { id: 'women-jeans',
       title: 'Jeans',
       items:
        [ { id: 111,
            name: 'Satin moleskin jean',
            imageURL: 'https://picsum.photos/id/111/200/300',
            price: 590 },
          { id: 112,
            name: 'Fabric moleskin jean',
            imageURL: 'https://picsum.photos/id/112/200/300',
            price: 457 },
          { id: 113,
            name: 'Crinoline glossy jean',
            imageURL: 'https://picsum.photos/id/113/200/300',
            price: 436 },
          { id: 114,
            name: 'Crinoline short jean',
            imageURL: 'https://picsum.photos/id/114/200/300',
            price: 592 },
          { id: 115,
            name: 'Linen fleck jean',
            imageURL: 'https://picsum.photos/id/115/200/300',
            price: 513 },
          { id: 116,
            name: 'Gabardine rubber jean',
            imageURL: 'https://picsum.photos/id/116/200/300',
            price: 479 },
          { id: 117,
            name: 'Baldachin glossy jean',
            imageURL: 'https://picsum.photos/id/117/200/300',
            price: 538 },
          { id: 118,
            name: 'Linen velvet jean',
            imageURL: 'https://picsum.photos/id/118/200/300',
            price: 446 },
          { id: 119,
            name: 'Gabardine chiffon jean',
            imageURL: 'https://picsum.photos/id/119/200/300',
            price: 496 },
          { id: 120,
            name: 'Satin organza jean',
            imageURL: 'https://picsum.photos/id/120/200/300',
            price: 591 } ] },
     { id: 'women-trousers',
       title: 'trousers',
       items:
        [ { id: 121,
            name: 'Denim moleskin trouser',
            imageURL: 'https://picsum.photos/id/121/200/300',
            price: 452 },
          { id: 122,
            name: 'Wool yarn trouser',
            imageURL: 'https://picsum.photos/id/122/200/300',
            price: 451 },
          { id: 123,
            name: 'Wool short trouser',
            imageURL: 'https://picsum.photos/id/123/200/300',
            price: 431 },
          { id: 124,
            name: 'Dungarees loom trouser',
            imageURL: 'https://picsum.photos/id/124/200/300',
            price: 480 },
          { id: 125,
            name: 'Baldachin sateen trouser',
            imageURL: 'https://picsum.photos/id/125/200/300',
            price: 451 },
          { id: 126,
            name: 'Linen venise trouser',
            imageURL: 'https://picsum.photos/id/126/200/300',
            price: 517 },
          { id: 127,
            name: 'Angora glossy trouser',
            imageURL: 'https://picsum.photos/id/127/200/300',
            price: 408 },
          { id: 128,
            name: 'Satin stiff trouser',
            imageURL: 'https://picsum.photos/id/128/200/300',
            price: 583 },
          { id: 129,
            name: 'Linen loom trouser',
            imageURL: 'https://picsum.photos/id/129/200/300',
            price: 404 },
          { id: 130,
            name: 'Flannel nylon trouser',
            imageURL: 'https://picsum.photos/id/130/200/300',
            price: 470 } ] },
     { id: 'women-jackets',
       title: 'Jackets',
       items:
        [ { id: 131,
            name: 'Damask chiffon jacket',
            imageURL: 'https://picsum.photos/id/131/200/300',
            price: 518 },
          { id: 132,
            name: 'Gabardine weave jacket',
            imageURL: 'https://picsum.photos/id/132/200/300',
            price: 530 },
          { id: 133,
            name: 'Damask tweed jacket',
            imageURL: 'https://picsum.photos/id/133/200/300',
            price: 476 },
          { id: 134,
            name: 'Satin lace jacket',
            imageURL: 'https://picsum.photos/id/134/200/300',
            price: 443 },
          { id: 135,
            name: 'blue loom jacket',
            imageURL: 'https://picsum.photos/id/135/200/300',
            price: 521 },
          { id: 136,
            name: 'Linen stiff jacket',
            imageURL: 'https://picsum.photos/id/136/200/300',
            price: 570 },
          { id: 137,
            name: 'Milled jacquard jacket',
            imageURL: 'https://picsum.photos/id/137/200/300',
            price: 510 },
          { id: 138,
            name: 'Satin moleskin jacket',
            imageURL: 'https://picsum.photos/id/138/200/300',
            price: 598 },
          { id: 139,
            name: 'Milled surface jacket',
            imageURL: 'https://picsum.photos/id/139/200/300',
            price: 453 },
          { id: 140,
            name: 'Cotton mohair jacket',
            imageURL: 'https://picsum.photos/id/140/200/300',
            price: 482 } ] },
     { id: 'women-hats',
       title: 'Hats',
       items:
        [ { id: 141,
            name: 'blue nylon hat',
            imageURL: 'https://picsum.photos/id/141/200/300',
            price: 517 },
          { id: 142,
            name: 'Damask lace hat',
            imageURL: 'https://picsum.photos/id/142/200/300',
            price: 598 },
          { id: 143,
            name: 'Damask tweed hat',
            imageURL: 'https://picsum.photos/id/143/200/300',
            price: 537 },
          { id: 144,
            name: 'Crinoline sateen hat',
            imageURL: 'https://picsum.photos/id/144/200/300',
            price: 492 },
          { id: 145,
            name: 'Fabric fleck hat',
            imageURL: 'https://picsum.photos/id/145/200/300',
            price: 424 },
          { id: 146,
            name: 'Pattern weave hat',
            imageURL: 'https://picsum.photos/id/146/200/300',
            price: 593 },
          { id: 147,
            name: 'Crinoline mohair hat',
            imageURL: 'https://picsum.photos/id/147/200/300',
            price: 577 },
          { id: 148,
            name: 'Satin fleck hat',
            imageURL: 'https://picsum.photos/id/148/200/300',
            price: 431 },
          { id: 149,
            name: 'Milled sateen hat',
            imageURL: 'https://picsum.photos/id/149/200/300',
            price: 515 },
          { id: 150,
            name: 'Corduroy chiffon hat',
            imageURL: 'https://picsum.photos/id/150/200/300',
            price: 549 } ] },
     { id: 'women-shirt',
       title: 'Shirt',
       items:
        [ { id: 151,
            name: 'Fabric chiffon shirt',
            imageURL: 'https://picsum.photos/id/151/200/300',
            price: 481 },
          { id: 152,
            name: 'blue mohair shirt',
            imageURL: 'https://picsum.photos/id/152/200/300',
            price: 523 },
          { id: 153,
            name: 'Denim moleskin shirt',
            imageURL: 'https://picsum.photos/id/153/200/300',
            price: 514 },
          { id: 154,
            name: 'Batiste jacquard shirt',
            imageURL: 'https://picsum.photos/id/154/200/300',
            price: 440 },
          { id: 155,
            name: 'Baldachin loom shirt',
            imageURL: 'https://picsum.photos/id/155/200/300',
            price: 441 },
          { id: 156,
            name: 'Linen fleck shirt',
            imageURL: 'https://picsum.photos/id/156/200/300',
            price: 537 },
          { id: 157,
            name: 'Denim glossy shirt',
            imageURL: 'https://picsum.photos/id/157/200/300',
            price: 415 },
          { id: 158,
            name: 'Damask jacquard shirt',
            imageURL: 'https://picsum.photos/id/158/200/300',
            price: 482 },
          { id: 159,
            name: 'Baldachin stiff shirt',
            imageURL: 'https://picsum.photos/id/159/200/300',
            price: 450 },
          { id: 160,
            name: 'blue moleskin shirt',
            imageURL: 'https://picsum.photos/id/160/200/300',
            price: 496 } ] },
     { id: 'women-tshirt',
       title: 'T-shirt',
       items:
        [ { id: 161,
            name: 'Denim weave t-shirt',
            imageURL: 'https://picsum.photos/id/161/200/300',
            price: 559 },
          { id: 162,
            name: 'Thread loom t-shirt',
            imageURL: 'https://picsum.photos/id/162/200/300',
            price: 489 },
          { id: 163,
            name: 'Thread nylon t-shirt',
            imageURL: 'https://picsum.photos/id/163/200/300',
            price: 545 },
          { id: 164,
            name: 'Linen short t-shirt',
            imageURL: 'https://picsum.photos/id/164/200/300',
            price: 530 },
          { id: 165,
            name: 'Linen tweed t-shirt',
            imageURL: 'https://picsum.photos/id/165/200/300',
            price: 531 },
          { id: 166,
            name: 'Dungarees moleskin t-shirt',
            imageURL: 'https://picsum.photos/id/166/200/300',
            price: 549 },
          { id: 167,
            name: 'Baldachin fleck t-shirt',
            imageURL: 'https://picsum.photos/id/167/200/300',
            price: 509 },
          { id: 168,
            name: 'Denim organza t-shirt',
            imageURL: 'https://picsum.photos/id/168/200/300',
            price: 452 },
          { id: 169,
            name: 'Thread lace t-shirt',
            imageURL: 'https://picsum.photos/id/169/200/300',
            price: 552 },
          { id: 170,
            name: 'Dungarees loom t-shirt',
            imageURL: 'https://picsum.photos/id/170/200/300',
            price: 413 } ] },
     { id: 'women-watches',
       title: 'watches',
       items:
        [ { id: 171,
            name: 'Fabric tweed watch',
            imageURL: 'https://picsum.photos/id/171/200/300',
            price: 557 },
          { id: 172,
            name: 'Thread chiffon watch',
            imageURL: 'https://picsum.photos/id/172/200/300',
            price: 460 },
          { id: 173,
            name: 'Baldachin glossy watch',
            imageURL: 'https://picsum.photos/id/173/200/300',
            price: 489 },
          { id: 174,
            name: 'Thread stiff watch',
            imageURL: 'https://picsum.photos/id/174/200/300',
            price: 569 },
          { id: 175,
            name: 'Crinoline venise watch',
            imageURL: 'https://picsum.photos/id/175/200/300',
            price: 407 },
          { id: 176,
            name: 'Satin glossy watch',
            imageURL: 'https://picsum.photos/id/176/200/300',
            price: 502 },
          { id: 177,
            name: 'Batiste tweed watch',
            imageURL: 'https://picsum.photos/id/177/200/300',
            price: 494 },
          { id: 178,
            name: 'Pattern loom watch',
            imageURL: 'https://picsum.photos/id/178/200/300',
            price: 559 },
          { id: 179,
            name: 'Batiste velvet watch',
            imageURL: 'https://picsum.photos/id/179/200/300',
            price: 479 },
          { id: 180,
            name: 'Batiste velvet watch',
            imageURL: 'https://picsum.photos/id/180/200/300',
            price: 486 } ] } ],
  boys:
   [ { id: 'boys-shoes',
       title: 'Shoes',
       items:
        [ { id: 181,
            name: 'Pattern jacquard shoe',
            imageURL: 'https://picsum.photos/id/181/200/300',
            price: 521 },
          { id: 182,
            name: 'Satin yarn shoe',
            imageURL: 'https://picsum.photos/id/182/200/300',
            price: 449 },
          { id: 183,
            name: 'Thread weave shoe',
            imageURL: 'https://picsum.photos/id/183/200/300',
            price: 475 },
          { id: 184,
            name: 'Milled surface shoe',
            imageURL: 'https://picsum.photos/id/184/200/300',
            price: 504 },
          { id: 185,
            name: 'Wool rubber shoe',
            imageURL: 'https://picsum.photos/id/185/200/300',
            price: 473 },
          { id: 186,
            name: 'Corduroy mohair shoe',
            imageURL: 'https://picsum.photos/id/186/200/300',
            price: 540 },
          { id: 187,
            name: 'Thread mohair shoe',
            imageURL: 'https://picsum.photos/id/187/200/300',
            price: 435 },
          { id: 188,
            name: 'Gabardine glossy shoe',
            imageURL: 'https://picsum.photos/id/188/200/300',
            price: 421 },
          { id: 189,
            name: 'Cotton glossy shoe',
            imageURL: 'https://picsum.photos/id/189/200/300',
            price: 553 },
          { id: 190,
            name: 'Batiste venise shoe',
            imageURL: 'https://picsum.photos/id/190/200/300',
            price: 596 } ] },
     { id: 'boys-socks',
       title: 'Socks',
       items:
        [ { id: 191,
            name: 'Gabardine stiff sock',
            imageURL: 'https://picsum.photos/id/191/200/300',
            price: 559 },
          { id: 192,
            name: 'Batiste velvet sock',
            imageURL: 'https://picsum.photos/id/192/200/300',
            price: 521 },
          { id: 193,
            name: 'Gabardine fleck sock',
            imageURL: 'https://picsum.photos/id/193/200/300',
            price: 552 },
          { id: 194,
            name: 'Wool nylon sock',
            imageURL: 'https://picsum.photos/id/194/200/300',
            price: 532 },
          { id: 195,
            name: 'Linen yarn sock',
            imageURL: 'https://picsum.photos/id/195/200/300',
            price: 529 },
          { id: 196,
            name: 'blue sateen sock',
            imageURL: 'https://picsum.photos/id/196/200/300',
            price: 599 },
          { id: 197,
            name: 'Cotton weave sock',
            imageURL: 'https://picsum.photos/id/197/200/300',
            price: 457 },
          { id: 198,
            name: 'blue nylon sock',
            imageURL: 'https://picsum.photos/id/198/200/300',
            price: 494 },
          { id: 199,
            name: 'Flannel jacquard sock',
            imageURL: 'https://picsum.photos/id/199/200/300',
            price: 583 },
          { id: 200,
            name: 'Damask rubber sock',
            imageURL: 'https://picsum.photos/id/200/200/300',
            price: 420 } ] },
     { id: 'boys-jeans',
       title: 'Jeans',
       items:
        [ { id: 201,
            name: 'Thread jacquard jean',
            imageURL: 'https://picsum.photos/id/201/200/300',
            price: 511 },
          { id: 202,
            name: 'Satin surface jean',
            imageURL: 'https://picsum.photos/id/202/200/300',
            price: 573 },
          { id: 203,
            name: 'Linen mohair jean',
            imageURL: 'https://picsum.photos/id/203/200/300',
            price: 544 },
          { id: 204,
            name: 'Batiste velvet jean',
            imageURL: 'https://picsum.photos/id/204/200/300',
            price: 483 },
          { id: 205,
            name: 'Batiste surface jean',
            imageURL: 'https://picsum.photos/id/205/200/300',
            price: 490 },
          { id: 206,
            name: 'Linen venise jean',
            imageURL: 'https://picsum.photos/id/206/200/300',
            price: 410 },
          { id: 207,
            name: 'Baldachin surface jean',
            imageURL: 'https://picsum.photos/id/207/200/300',
            price: 411 },
          { id: 208,
            name: 'Thread fleck jean',
            imageURL: 'https://picsum.photos/id/208/200/300',
            price: 494 },
          { id: 209,
            name: 'Gabardine fleck jean',
            imageURL: 'https://picsum.photos/id/209/200/300',
            price: 413 },
          { id: 210,
            name: 'Angora sateen jean',
            imageURL: 'https://picsum.photos/id/210/200/300',
            price: 540 } ] },
     { id: 'boys-trousers',
       title: 'trousers',
       items:
        [ { id: 211,
            name: 'Flannel surface trouser',
            imageURL: 'https://picsum.photos/id/211/200/300',
            price: 421 },
          { id: 212,
            name: 'Damask tweed trouser',
            imageURL: 'https://picsum.photos/id/212/200/300',
            price: 558 },
          { id: 213,
            name: 'Crinoline stiff trouser',
            imageURL: 'https://picsum.photos/id/213/200/300',
            price: 530 },
          { id: 214,
            name: 'Corduroy moleskin trouser',
            imageURL: 'https://picsum.photos/id/214/200/300',
            price: 422 },
          { id: 215,
            name: 'Damask moleskin trouser',
            imageURL: 'https://picsum.photos/id/215/200/300',
            price: 525 },
          { id: 216,
            name: 'blue lace trouser',
            imageURL: 'https://picsum.photos/id/216/200/300',
            price: 591 },
          { id: 217,
            name: 'Milled mohair trouser',
            imageURL: 'https://picsum.photos/id/217/200/300',
            price: 525 },
          { id: 218,
            name: 'Satin jacquard trouser',
            imageURL: 'https://picsum.photos/id/218/200/300',
            price: 518 },
          { id: 219,
            name: 'Cotton stiff trouser',
            imageURL: 'https://picsum.photos/id/219/200/300',
            price: 574 },
          { id: 220,
            name: 'Linen glossy trouser',
            imageURL: 'https://picsum.photos/id/220/200/300',
            price: 551 } ] },
     { id: 'boys-jackets',
       title: 'Jackets',
       items:
        [ { id: 221,
            name: 'Baft lace jacket',
            imageURL: 'https://picsum.photos/id/221/200/300',
            price: 426 },
          { id: 222,
            name: 'Pattern lace jacket',
            imageURL: 'https://picsum.photos/id/222/200/300',
            price: 451 },
          { id: 223,
            name: 'Angora lace jacket',
            imageURL: 'https://picsum.photos/id/223/200/300',
            price: 440 },
          { id: 224,
            name: 'Flannel venise jacket',
            imageURL: 'https://picsum.photos/id/224/200/300',
            price: 596 },
          { id: 225,
            name: 'Batiste rubber jacket',
            imageURL: 'https://picsum.photos/id/225/200/300',
            price: 576 },
          { id: 226,
            name: 'Angora mohair jacket',
            imageURL: 'https://picsum.photos/id/226/200/300',
            price: 556 },
          { id: 227,
            name: 'blue rubber jacket',
            imageURL: 'https://picsum.photos/id/227/200/300',
            price: 584 },
          { id: 228,
            name: 'Angora weave jacket',
            imageURL: 'https://picsum.photos/id/228/200/300',
            price: 549 },
          { id: 229,
            name: 'Fabric sateen jacket',
            imageURL: 'https://picsum.photos/id/229/200/300',
            price: 584 },
          { id: 230,
            name: 'Baft weave jacket',
            imageURL: 'https://picsum.photos/id/230/200/300',
            price: 595 } ] },
     { id: 'boys-hats',
       title: 'Hats',
       items:
        [ { id: 231,
            name: 'Baft rubber hat',
            imageURL: 'https://picsum.photos/id/231/200/300',
            price: 420 },
          { id: 232,
            name: 'Gabardine yarn hat',
            imageURL: 'https://picsum.photos/id/232/200/300',
            price: 578 },
          { id: 233,
            name: 'Batiste lace hat',
            imageURL: 'https://picsum.photos/id/233/200/300',
            price: 598 },
          { id: 234,
            name: 'Linen rubber hat',
            imageURL: 'https://picsum.photos/id/234/200/300',
            price: 489 },
          { id: 235,
            name: 'Gabardine velvet hat',
            imageURL: 'https://picsum.photos/id/235/200/300',
            price: 545 },
          { id: 236,
            name: 'Gabardine yarn hat',
            imageURL: 'https://picsum.photos/id/236/200/300',
            price: 599 },
          { id: 237,
            name: 'Angora rubber hat',
            imageURL: 'https://picsum.photos/id/237/200/300',
            price: 581 },
          { id: 238,
            name: 'Dungarees velvet hat',
            imageURL: 'https://picsum.photos/id/238/200/300',
            price: 412 },
          { id: 239,
            name: 'Corduroy venise hat',
            imageURL: 'https://picsum.photos/id/239/200/300',
            price: 539 },
          { id: 240,
            name: 'Baft short hat',
            imageURL: 'https://picsum.photos/id/240/200/300',
            price: 546 } ] },
     { id: 'boys-shirt',
       title: 'Shirt',
       items:
        [ { id: 241,
            name: 'blue sateen shirt',
            imageURL: 'https://picsum.photos/id/241/200/300',
            price: 503 },
          { id: 242,
            name: 'Flannel weave shirt',
            imageURL: 'https://picsum.photos/id/242/200/300',
            price: 445 },
          { id: 243,
            name: 'Cotton glossy shirt',
            imageURL: 'https://picsum.photos/id/243/200/300',
            price: 439 },
          { id: 244,
            name: 'Baldachin weave shirt',
            imageURL: 'https://picsum.photos/id/244/200/300',
            price: 467 },
          { id: 245,
            name: 'Linen velvet shirt',
            imageURL: 'https://picsum.photos/id/245/200/300',
            price: 422 },
          { id: 246,
            name: 'Gabardine venise shirt',
            imageURL: 'https://picsum.photos/id/246/200/300',
            price: 463 },
          { id: 247,
            name: 'Baft glossy shirt',
            imageURL: 'https://picsum.photos/id/247/200/300',
            price: 569 },
          { id: 248,
            name: 'Denim weave shirt',
            imageURL: 'https://picsum.photos/id/248/200/300',
            price: 435 },
          { id: 249,
            name: 'Baft venise shirt',
            imageURL: 'https://picsum.photos/id/249/200/300',
            price: 575 },
          { id: 250,
            name: 'Flannel mohair shirt',
            imageURL: 'https://picsum.photos/id/250/200/300',
            price: 501 } ] },
     { id: 'boys-tshirt',
       title: 'T-shirt',
       items:
        [ { id: 251,
            name: 'Dungarees stiff t-shirt',
            imageURL: 'https://picsum.photos/id/251/200/300',
            price: 470 },
          { id: 252,
            name: 'Baldachin surface t-shirt',
            imageURL: 'https://picsum.photos/id/252/200/300',
            price: 441 },
          { id: 253,
            name: 'Wool glossy t-shirt',
            imageURL: 'https://picsum.photos/id/253/200/300',
            price: 464 },
          { id: 254,
            name: 'Linen venise t-shirt',
            imageURL: 'https://picsum.photos/id/254/200/300',
            price: 409 },
          { id: 255,
            name: 'Milled rubber t-shirt',
            imageURL: 'https://picsum.photos/id/255/200/300',
            price: 437 },
          { id: 256,
            name: 'Thread loom t-shirt',
            imageURL: 'https://picsum.photos/id/256/200/300',
            price: 567 },
          { id: 257,
            name: 'Milled surface t-shirt',
            imageURL: 'https://picsum.photos/id/257/200/300',
            price: 566 },
          { id: 258,
            name: 'Dungarees mohair t-shirt',
            imageURL: 'https://picsum.photos/id/258/200/300',
            price: 451 },
          { id: 259,
            name: 'Crinoline loom t-shirt',
            imageURL: 'https://picsum.photos/id/259/200/300',
            price: 436 },
          { id: 260,
            name: 'Damask glossy t-shirt',
            imageURL: 'https://picsum.photos/id/260/200/300',
            price: 505 } ] },
     { id: 'boys-watches',
       title: 'watches',
       items:
        [ { id: 261,
            name: 'Crinoline glossy watch',
            imageURL: 'https://picsum.photos/id/261/200/300',
            price: 593 },
          { id: 262,
            name: 'Angora nylon watch',
            imageURL: 'https://picsum.photos/id/262/200/300',
            price: 569 },
          { id: 263,
            name: 'blue rubber watch',
            imageURL: 'https://picsum.photos/id/263/200/300',
            price: 590 },
          { id: 264,
            name: 'Fabric rubber watch',
            imageURL: 'https://picsum.photos/id/264/200/300',
            price: 584 },
          { id: 265,
            name: 'Linen stiff watch',
            imageURL: 'https://picsum.photos/id/265/200/300',
            price: 516 },
          { id: 266,
            name: 'Pattern moleskin watch',
            imageURL: 'https://picsum.photos/id/266/200/300',
            price: 578 },
          { id: 267,
            name: 'Angora lace watch',
            imageURL: 'https://picsum.photos/id/267/200/300',
            price: 549 },
          { id: 268,
            name: 'Dungarees organza watch',
            imageURL: 'https://picsum.photos/id/268/200/300',
            price: 591 },
          { id: 269,
            name: 'Cotton organza watch',
            imageURL: 'https://picsum.photos/id/269/200/300',
            price: 503 },
          { id: 270,
            name: 'Milled loom watch',
            imageURL: 'https://picsum.photos/id/270/200/300',
            price: 460 } ] } ],
  girls:
   [ { id: 'girls-shoes',
       title: 'Shoes',
       items:
        [ { id: 271,
            name: 'Flannel organza shoe',
            imageURL: 'https://picsum.photos/id/271/200/300',
            price: 416 },
          { id: 272,
            name: 'Linen nylon shoe',
            imageURL: 'https://picsum.photos/id/272/200/300',
            price: 506 },
          { id: 273,
            name: 'Denim chiffon shoe',
            imageURL: 'https://picsum.photos/id/273/200/300',
            price: 566 },
          { id: 274,
            name: 'Flannel mohair shoe',
            imageURL: 'https://picsum.photos/id/274/200/300',
            price: 539 },
          { id: 275,
            name: 'Wool surface shoe',
            imageURL: 'https://picsum.photos/id/275/200/300',
            price: 488 },
          { id: 276,
            name: 'Wool glossy shoe',
            imageURL: 'https://picsum.photos/id/276/200/300',
            price: 456 },
          { id: 277,
            name: 'Gabardine weave shoe',
            imageURL: 'https://picsum.photos/id/277/200/300',
            price: 555 },
          { id: 278,
            name: 'blue chiffon shoe',
            imageURL: 'https://picsum.photos/id/278/200/300',
            price: 593 },
          { id: 279,
            name: 'Dungarees fleck shoe',
            imageURL: 'https://picsum.photos/id/279/200/300',
            price: 402 },
          { id: 280,
            name: 'Pattern loom shoe',
            imageURL: 'https://picsum.photos/id/280/200/300',
            price: 445 } ] },
     { id: 'girls-socks',
       title: 'Socks',
       items:
        [ { id: 281,
            name: 'Baft glossy sock',
            imageURL: 'https://picsum.photos/id/281/200/300',
            price: 454 },
          { id: 282,
            name: 'Fabric rubber sock',
            imageURL: 'https://picsum.photos/id/282/200/300',
            price: 503 },
          { id: 283,
            name: 'Angora short sock',
            imageURL: 'https://picsum.photos/id/283/200/300',
            price: 568 },
          { id: 284,
            name: 'Cotton fleck sock',
            imageURL: 'https://picsum.photos/id/284/200/300',
            price: 448 },
          { id: 285,
            name: 'Damask velvet sock',
            imageURL: 'https://picsum.photos/id/285/200/300',
            price: 552 },
          { id: 286,
            name: 'Cotton stiff sock',
            imageURL: 'https://picsum.photos/id/286/200/300',
            price: 534 },
          { id: 287,
            name: 'Denim rubber sock',
            imageURL: 'https://picsum.photos/id/287/200/300',
            price: 419 },
          { id: 288,
            name: 'Dungarees moleskin sock',
            imageURL: 'https://picsum.photos/id/288/200/300',
            price: 579 },
          { id: 289,
            name: 'Baft loom sock',
            imageURL: 'https://picsum.photos/id/289/200/300',
            price: 524 },
          { id: 290,
            name: 'Angora moleskin sock',
            imageURL: 'https://picsum.photos/id/290/200/300',
            price: 544 } ] },
     { id: 'girls-jeans',
       title: 'Jeans',
       items:
        [ { id: 291,
            name: 'Pattern weave jean',
            imageURL: 'https://picsum.photos/id/291/200/300',
            price: 568 },
          { id: 292,
            name: 'blue short jean',
            imageURL: 'https://picsum.photos/id/292/200/300',
            price: 499 },
          { id: 293,
            name: 'Linen surface jean',
            imageURL: 'https://picsum.photos/id/293/200/300',
            price: 456 },
          { id: 294,
            name: 'Cotton venise jean',
            imageURL: 'https://picsum.photos/id/294/200/300',
            price: 435 },
          { id: 295,
            name: 'Baldachin sateen jean',
            imageURL: 'https://picsum.photos/id/295/200/300',
            price: 544 },
          { id: 296,
            name: 'Milled tweed jean',
            imageURL: 'https://picsum.photos/id/296/200/300',
            price: 477 },
          { id: 297,
            name: 'Thread surface jean',
            imageURL: 'https://picsum.photos/id/297/200/300',
            price: 469 },
          { id: 298,
            name: 'blue tweed jean',
            imageURL: 'https://picsum.photos/id/298/200/300',
            price: 462 },
          { id: 299,
            name: 'Linen short jean',
            imageURL: 'https://picsum.photos/id/299/200/300',
            price: 485 },
          { id: 300,
            name: 'Batiste weave jean',
            imageURL: 'https://picsum.photos/id/300/200/300',
            price: 532 } ] },
     { id: 'girls-trousers',
       title: 'trousers',
       items:
        [ { id: 301,
            name: 'Satin moleskin trouser',
            imageURL: 'https://picsum.photos/id/301/200/300',
            price: 458 },
          { id: 302,
            name: 'Denim stiff trouser',
            imageURL: 'https://picsum.photos/id/302/200/300',
            price: 441 },
          { id: 303,
            name: 'Thread short trouser',
            imageURL: 'https://picsum.photos/id/303/200/300',
            price: 407 },
          { id: 304,
            name: 'Gabardine velvet trouser',
            imageURL: 'https://picsum.photos/id/304/200/300',
            price: 466 },
          { id: 305,
            name: 'Angora chiffon trouser',
            imageURL: 'https://picsum.photos/id/305/200/300',
            price: 473 },
          { id: 306,
            name: 'Dungarees short trouser',
            imageURL: 'https://picsum.photos/id/306/200/300',
            price: 564 },
          { id: 307,
            name: 'Thread lace trouser',
            imageURL: 'https://picsum.photos/id/307/200/300',
            price: 431 },
          { id: 308,
            name: 'blue nylon trouser',
            imageURL: 'https://picsum.photos/id/308/200/300',
            price: 508 },
          { id: 309,
            name: 'Thread jacquard trouser',
            imageURL: 'https://picsum.photos/id/309/200/300',
            price: 532 },
          { id: 310,
            name: 'Thread organza trouser',
            imageURL: 'https://picsum.photos/id/310/200/300',
            price: 581 } ] },
     { id: 'girls-jackets',
       title: 'Jackets',
       items:
        [ { id: 311,
            name: 'Milled moleskin jacket',
            imageURL: 'https://picsum.photos/id/311/200/300',
            price: 405 },
          { id: 312,
            name: 'Linen yarn jacket',
            imageURL: 'https://picsum.photos/id/312/200/300',
            price: 579 },
          { id: 313,
            name: 'Fabric jacquard jacket',
            imageURL: 'https://picsum.photos/id/313/200/300',
            price: 448 },
          { id: 314,
            name: 'Angora organza jacket',
            imageURL: 'https://picsum.photos/id/314/200/300',
            price: 456 },
          { id: 315,
            name: 'Baft organza jacket',
            imageURL: 'https://picsum.photos/id/315/200/300',
            price: 548 },
          { id: 316,
            name: 'Milled mohair jacket',
            imageURL: 'https://picsum.photos/id/316/200/300',
            price: 528 },
          { id: 317,
            name: 'Gabardine yarn jacket',
            imageURL: 'https://picsum.photos/id/317/200/300',
            price: 585 },
          { id: 318,
            name: 'Batiste organza jacket',
            imageURL: 'https://picsum.photos/id/318/200/300',
            price: 402 },
          { id: 319,
            name: 'Pattern nylon jacket',
            imageURL: 'https://picsum.photos/id/319/200/300',
            price: 537 },
          { id: 320,
            name: 'Satin fleck jacket',
            imageURL: 'https://picsum.photos/id/320/200/300',
            price: 569 } ] },
     { id: 'girls-hats',
       title: 'Hats',
       items:
        [ { id: 321,
            name: 'Thread moleskin hat',
            imageURL: 'https://picsum.photos/id/321/200/300',
            price: 563 },
          { id: 322,
            name: 'Damask loom hat',
            imageURL: 'https://picsum.photos/id/322/200/300',
            price: 495 },
          { id: 323,
            name: 'Damask yarn hat',
            imageURL: 'https://picsum.photos/id/323/200/300',
            price: 500 },
          { id: 324,
            name: 'Angora mohair hat',
            imageURL: 'https://picsum.photos/id/324/200/300',
            price: 558 },
          { id: 325,
            name: 'Batiste yarn hat',
            imageURL: 'https://picsum.photos/id/325/200/300',
            price: 509 },
          { id: 326,
            name: 'Pattern rubber hat',
            imageURL: 'https://picsum.photos/id/326/200/300',
            price: 538 },
          { id: 327,
            name: 'Batiste velvet hat',
            imageURL: 'https://picsum.photos/id/327/200/300',
            price: 518 },
          { id: 328,
            name: 'Wool organza hat',
            imageURL: 'https://picsum.photos/id/328/200/300',
            price: 550 },
          { id: 329,
            name: 'Linen tweed hat',
            imageURL: 'https://picsum.photos/id/329/200/300',
            price: 421 },
          { id: 330,
            name: 'Flannel velvet hat',
            imageURL: 'https://picsum.photos/id/330/200/300',
            price: 528 } ] },
     { id: 'girls-shirt',
       title: 'Shirt',
       items:
        [ { id: 331,
            name: 'Damask sateen shirt',
            imageURL: 'https://picsum.photos/id/331/200/300',
            price: 441 },
          { id: 332,
            name: 'Corduroy tweed shirt',
            imageURL: 'https://picsum.photos/id/332/200/300',
            price: 425 },
          { id: 333,
            name: 'Satin yarn shirt',
            imageURL: 'https://picsum.photos/id/333/200/300',
            price: 416 },
          { id: 334,
            name: 'Corduroy organza shirt',
            imageURL: 'https://picsum.photos/id/334/200/300',
            price: 573 },
          { id: 335,
            name: 'Satin rubber shirt',
            imageURL: 'https://picsum.photos/id/335/200/300',
            price: 558 },
          { id: 336,
            name: 'Gabardine surface shirt',
            imageURL: 'https://picsum.photos/id/336/200/300',
            price: 471 },
          { id: 337,
            name: 'Thread short shirt',
            imageURL: 'https://picsum.photos/id/337/200/300',
            price: 415 },
          { id: 338,
            name: 'Gabardine loom shirt',
            imageURL: 'https://picsum.photos/id/338/200/300',
            price: 506 },
          { id: 339,
            name: 'Fabric nylon shirt',
            imageURL: 'https://picsum.photos/id/339/200/300',
            price: 509 },
          { id: 340,
            name: 'Milled sateen shirt',
            imageURL: 'https://picsum.photos/id/340/200/300',
            price: 541 } ] },
     { id: 'girls-tshirt',
       title: 'T-shirt',
       items:
        [ { id: 341,
            name: 'Milled rubber t-shirt',
            imageURL: 'https://picsum.photos/id/341/200/300',
            price: 478 },
          { id: 342,
            name: 'Damask chiffon t-shirt',
            imageURL: 'https://picsum.photos/id/342/200/300',
            price: 420 },
          { id: 343,
            name: 'Crinoline glossy t-shirt',
            imageURL: 'https://picsum.photos/id/343/200/300',
            price: 478 },
          { id: 344,
            name: 'Denim mohair t-shirt',
            imageURL: 'https://picsum.photos/id/344/200/300',
            price: 530 },
          { id: 345,
            name: 'blue sateen t-shirt',
            imageURL: 'https://picsum.photos/id/345/200/300',
            price: 435 },
          { id: 346,
            name: 'Linen sateen t-shirt',
            imageURL: 'https://picsum.photos/id/346/200/300',
            price: 421 },
          { id: 347,
            name: 'Crinoline glossy t-shirt',
            imageURL: 'https://picsum.photos/id/347/200/300',
            price: 489 },
          { id: 348,
            name: 'Cotton stiff t-shirt',
            imageURL: 'https://picsum.photos/id/348/200/300',
            price: 404 },
          { id: 349,
            name: 'blue weave t-shirt',
            imageURL: 'https://picsum.photos/id/349/200/300',
            price: 446 },
          { id: 350,
            name: 'Cotton venise t-shirt',
            imageURL: 'https://picsum.photos/id/350/200/300',
            price: 450 } ] },
     { id: 'girls-watches',
       title: 'watches',
       items:
        [ { id: 351,
            name: 'Denim venise watch',
            imageURL: 'https://picsum.photos/id/351/200/300',
            price: 577 },
          { id: 352,
            name: 'blue stiff watch',
            imageURL: 'https://picsum.photos/id/352/200/300',
            price: 440 },
          { id: 353,
            name: 'Batiste tweed watch',
            imageURL: 'https://picsum.photos/id/353/200/300',
            price: 451 },
          { id: 354,
            name: 'Damask tweed watch',
            imageURL: 'https://picsum.photos/id/354/200/300',
            price: 586 },
          { id: 355,
            name: 'Damask glossy watch',
            imageURL: 'https://picsum.photos/id/355/200/300',
            price: 474 },
          { id: 356,
            name: 'Milled weave watch',
            imageURL: 'https://picsum.photos/id/356/200/300',
            price: 558 },
          { id: 357,
            name: 'Damask fleck watch',
            imageURL: 'https://picsum.photos/id/357/200/300',
            price: 445 },
          { id: 358,
            name: 'Linen surface watch',
            imageURL: 'https://picsum.photos/id/358/200/300',
            price: 441 },
          { id: 359,
            name: 'blue sateen watch',
            imageURL: 'https://picsum.photos/id/359/200/300',
            price: 578 },
          { id: 360,
            name: 'Thread jacquard watch',
            imageURL: 'https://picsum.photos/id/360/200/300',
            price: 420 } ] } ] }
export default SHOP_DATA