const SHOP_DATA = { mens:
   { shoes:
      { id: 'men-shoes',
        title: 'Shoes',
        items:
         [ { id: 1,
             name: 'Fabric moleskin shoe',
             imageUrl: 'https://picsum.photos/id/1/200/300',
             price: 508 },
           { id: 2,
             name: 'Fabric tweed shoe',
             imageUrl: 'https://picsum.photos/id/2/200/300',
             price: 531 },
           { id: 3,
             name: 'Wool weave shoe',
             imageUrl: 'https://picsum.photos/id/3/200/300',
             price: 575 },
           { id: 4,
             name: 'Denim rubber shoe',
             imageUrl: 'https://picsum.photos/id/4/200/300',
             price: 492 },
           { id: 5,
             name: 'Corduroy loom shoe',
             imageUrl: 'https://picsum.photos/id/5/200/300',
             price: 434 },
           { id: 6,
             name: 'Flannel lace shoe',
             imageUrl: 'https://picsum.photos/id/6/200/300',
             price: 453 },
           { id: 7,
             name: 'Cotton moleskin shoe',
             imageUrl: 'https://picsum.photos/id/7/200/300',
             price: 498 },
           { id: 8,
             name: 'Gabardine nylon shoe',
             imageUrl: 'https://picsum.photos/id/8/200/300',
             price: 563 },
           { id: 9,
             name: 'Satin glossy shoe',
             imageUrl: 'https://picsum.photos/id/9/200/300',
             price: 424 },
           { id: 10,
             name: 'Corduroy organza shoe',
             imageUrl: 'https://picsum.photos/id/10/200/300',
             price: 575 } ] },
     socks:
      { id: 'men-socks',
        title: 'Socks',
        items:
         [ { id: 11,
             name: 'Baldachin organza sock',
             imageUrl: 'https://picsum.photos/id/11/200/300',
             price: 422 },
           { id: 12,
             name: 'Flannel short sock',
             imageUrl: 'https://picsum.photos/id/12/200/300',
             price: 405 },
           { id: 13,
             name: 'Crinoline venise sock',
             imageUrl: 'https://picsum.photos/id/13/200/300',
             price: 575 },
           { id: 14,
             name: 'Crinoline chiffon sock',
             imageUrl: 'https://picsum.photos/id/14/200/300',
             price: 509 },
           { id: 15,
             name: 'Cotton mohair sock',
             imageUrl: 'https://picsum.photos/id/15/200/300',
             price: 427 },
           { id: 16,
             name: 'Damask nylon sock',
             imageUrl: 'https://picsum.photos/id/16/200/300',
             price: 486 },
           { id: 17,
             name: 'Fabric velvet sock',
             imageUrl: 'https://picsum.photos/id/17/200/300',
             price: 415 },
           { id: 18,
             name: 'blue organza sock',
             imageUrl: 'https://picsum.photos/id/18/200/300',
             price: 585 },
           { id: 19,
             name: 'Denim nylon sock',
             imageUrl: 'https://picsum.photos/id/19/200/300',
             price: 517 },
           { id: 20,
             name: 'Baft moleskin sock',
             imageUrl: 'https://picsum.photos/id/20/200/300',
             price: 413 } ] },
     jeans:
      { id: 'men-jeans',
        title: 'Jeans',
        items:
         [ { id: 21,
             name: 'Linen surface jean',
             imageUrl: 'https://picsum.photos/id/21/200/300',
             price: 581 },
           { id: 22,
             name: 'Baft moleskin jean',
             imageUrl: 'https://picsum.photos/id/22/200/300',
             price: 476 },
           { id: 23,
             name: 'Corduroy lace jean',
             imageUrl: 'https://picsum.photos/id/23/200/300',
             price: 449 },
           { id: 24,
             name: 'Corduroy organza jean',
             imageUrl: 'https://picsum.photos/id/24/200/300',
             price: 416 },
           { id: 25,
             name: 'Cotton chiffon jean',
             imageUrl: 'https://picsum.photos/id/25/200/300',
             price: 435 },
           { id: 26,
             name: 'Damask lace jean',
             imageUrl: 'https://picsum.photos/id/26/200/300',
             price: 506 },
           { id: 27,
             name: 'Corduroy fleck jean',
             imageUrl: 'https://picsum.photos/id/27/200/300',
             price: 434 },
           { id: 28,
             name: 'Crinoline venise jean',
             imageUrl: 'https://picsum.photos/id/28/200/300',
             price: 478 },
           { id: 29,
             name: 'Baft venise jean',
             imageUrl: 'https://picsum.photos/id/29/200/300',
             price: 500 },
           { id: 30,
             name: 'Angora velvet jean',
             imageUrl: 'https://picsum.photos/id/30/200/300',
             price: 486 } ] },
     trousers:
      { id: 'men-trousers',
        title: 'trousers',
        items:
         [ { id: 31,
             name: 'Cotton glossy trouser',
             imageUrl: 'https://picsum.photos/id/31/200/300',
             price: 573 },
           { id: 32,
             name: 'Cotton loom trouser',
             imageUrl: 'https://picsum.photos/id/32/200/300',
             price: 598 },
           { id: 33,
             name: 'Milled stiff trouser',
             imageUrl: 'https://picsum.photos/id/33/200/300',
             price: 409 },
           { id: 34,
             name: 'Linen jacquard trouser',
             imageUrl: 'https://picsum.photos/id/34/200/300',
             price: 552 },
           { id: 35,
             name: 'Cotton velvet trouser',
             imageUrl: 'https://picsum.photos/id/35/200/300',
             price: 595 },
           { id: 36,
             name: 'Denim chiffon trouser',
             imageUrl: 'https://picsum.photos/id/36/200/300',
             price: 413 },
           { id: 37,
             name: 'Flannel moleskin trouser',
             imageUrl: 'https://picsum.photos/id/37/200/300',
             price: 480 },
           { id: 38,
             name: 'Satin chiffon trouser',
             imageUrl: 'https://picsum.photos/id/38/200/300',
             price: 539 },
           { id: 39,
             name: 'Gabardine velvet trouser',
             imageUrl: 'https://picsum.photos/id/39/200/300',
             price: 555 },
           { id: 40,
             name: 'Dungarees surface trouser',
             imageUrl: 'https://picsum.photos/id/40/200/300',
             price: 528 } ] },
     jackets:
      { id: 'men-jackets',
        title: 'Jackets',
        items:
         [ { id: 41,
             name: 'Linen nylon jacket',
             imageUrl: 'https://picsum.photos/id/41/200/300',
             price: 462 },
           { id: 42,
             name: 'Milled organza jacket',
             imageUrl: 'https://picsum.photos/id/42/200/300',
             price: 434 },
           { id: 43,
             name: 'Baldachin sateen jacket',
             imageUrl: 'https://picsum.photos/id/43/200/300',
             price: 567 },
           { id: 44,
             name: 'Damask fleck jacket',
             imageUrl: 'https://picsum.photos/id/44/200/300',
             price: 508 },
           { id: 45,
             name: 'Batiste lace jacket',
             imageUrl: 'https://picsum.photos/id/45/200/300',
             price: 575 },
           { id: 46,
             name: 'Baft lace jacket',
             imageUrl: 'https://picsum.photos/id/46/200/300',
             price: 452 },
           { id: 47,
             name: 'Pattern lace jacket',
             imageUrl: 'https://picsum.photos/id/47/200/300',
             price: 522 },
           { id: 48,
             name: 'Corduroy velvet jacket',
             imageUrl: 'https://picsum.photos/id/48/200/300',
             price: 564 },
           { id: 49,
             name: 'Wool jacquard jacket',
             imageUrl: 'https://picsum.photos/id/49/200/300',
             price: 507 },
           { id: 50,
             name: 'Corduroy loom jacket',
             imageUrl: 'https://picsum.photos/id/50/200/300',
             price: 557 } ] },
     hats:
      { id: 'men-hats',
        title: 'Hats',
        items:
         [ { id: 51,
             name: 'Corduroy weave hat',
             imageUrl: 'https://picsum.photos/id/51/200/300',
             price: 555 },
           { id: 52,
             name: 'Milled mohair hat',
             imageUrl: 'https://picsum.photos/id/52/200/300',
             price: 531 },
           { id: 53,
             name: 'Dungarees rubber hat',
             imageUrl: 'https://picsum.photos/id/53/200/300',
             price: 529 },
           { id: 54,
             name: 'Baldachin organza hat',
             imageUrl: 'https://picsum.photos/id/54/200/300',
             price: 536 },
           { id: 55,
             name: 'Baldachin chiffon hat',
             imageUrl: 'https://picsum.photos/id/55/200/300',
             price: 549 },
           { id: 56,
             name: 'Linen weave hat',
             imageUrl: 'https://picsum.photos/id/56/200/300',
             price: 540 },
           { id: 57,
             name: 'Gabardine sateen hat',
             imageUrl: 'https://picsum.photos/id/57/200/300',
             price: 595 },
           { id: 58,
             name: 'Satin organza hat',
             imageUrl: 'https://picsum.photos/id/58/200/300',
             price: 574 },
           { id: 59,
             name: 'Baft velvet hat',
             imageUrl: 'https://picsum.photos/id/59/200/300',
             price: 517 },
           { id: 60,
             name: 'Flannel surface hat',
             imageUrl: 'https://picsum.photos/id/60/200/300',
             price: 511 } ] },
     shirt:
      { id: 'men-shirt',
        title: 'Shirt',
        items:
         [ { id: 61,
             name: 'Satin surface shirt',
             imageUrl: 'https://picsum.photos/id/61/200/300',
             price: 474 },
           { id: 62,
             name: 'Milled velvet shirt',
             imageUrl: 'https://picsum.photos/id/62/200/300',
             price: 467 },
           { id: 63,
             name: 'Batiste sateen shirt',
             imageUrl: 'https://picsum.photos/id/63/200/300',
             price: 505 },
           { id: 64,
             name: 'Satin fleck shirt',
             imageUrl: 'https://picsum.photos/id/64/200/300',
             price: 411 },
           { id: 65,
             name: 'blue fleck shirt',
             imageUrl: 'https://picsum.photos/id/65/200/300',
             price: 556 },
           { id: 66,
             name: 'Pattern organza shirt',
             imageUrl: 'https://picsum.photos/id/66/200/300',
             price: 469 },
           { id: 67,
             name: 'Dungarees weave shirt',
             imageUrl: 'https://picsum.photos/id/67/200/300',
             price: 472 },
           { id: 68,
             name: 'Milled loom shirt',
             imageUrl: 'https://picsum.photos/id/68/200/300',
             price: 492 },
           { id: 69,
             name: 'Batiste yarn shirt',
             imageUrl: 'https://picsum.photos/id/69/200/300',
             price: 570 },
           { id: 70,
             name: 'Damask surface shirt',
             imageUrl: 'https://picsum.photos/id/70/200/300',
             price: 434 } ] },
     tshirt:
      { id: 'men-tshirt',
        title: 'T-shirt',
        items:
         [ { id: 71,
             name: 'Wool venise t-shirt',
             imageUrl: 'https://picsum.photos/id/71/200/300',
             price: 587 },
           { id: 72,
             name: 'Angora surface t-shirt',
             imageUrl: 'https://picsum.photos/id/72/200/300',
             price: 591 },
           { id: 73,
             name: 'Linen glossy t-shirt',
             imageUrl: 'https://picsum.photos/id/73/200/300',
             price: 590 },
           { id: 74,
             name: 'Flannel organza t-shirt',
             imageUrl: 'https://picsum.photos/id/74/200/300',
             price: 574 },
           { id: 75,
             name: 'Corduroy loom t-shirt',
             imageUrl: 'https://picsum.photos/id/75/200/300',
             price: 554 },
           { id: 76,
             name: 'Linen jacquard t-shirt',
             imageUrl: 'https://picsum.photos/id/76/200/300',
             price: 596 },
           { id: 77,
             name: 'Flannel glossy t-shirt',
             imageUrl: 'https://picsum.photos/id/77/200/300',
             price: 448 },
           { id: 78,
             name: 'Baft venise t-shirt',
             imageUrl: 'https://picsum.photos/id/78/200/300',
             price: 474 },
           { id: 79,
             name: 'Denim rubber t-shirt',
             imageUrl: 'https://picsum.photos/id/79/200/300',
             price: 460 },
           { id: 80,
             name: 'Gabardine tweed t-shirt',
             imageUrl: 'https://picsum.photos/id/80/200/300',
             price: 421 } ] },
     watches:
      { id: 'men-watches',
        title: 'watches',
        items:
         [ { id: 81,
             name: 'Crinoline loom watch',
             imageUrl: 'https://picsum.photos/id/81/200/300',
             price: 455 },
           { id: 82,
             name: 'Flannel stiff watch',
             imageUrl: 'https://picsum.photos/id/82/200/300',
             price: 423 },
           { id: 83,
             name: 'Angora weave watch',
             imageUrl: 'https://picsum.photos/id/83/200/300',
             price: 547 },
           { id: 84,
             name: 'Cotton tweed watch',
             imageUrl: 'https://picsum.photos/id/84/200/300',
             price: 449 },
           { id: 85,
             name: 'Wool fleck watch',
             imageUrl: 'https://picsum.photos/id/85/200/300',
             price: 405 },
           { id: 86,
             name: 'Pattern nylon watch',
             imageUrl: 'https://picsum.photos/id/86/200/300',
             price: 456 },
           { id: 87,
             name: 'Flannel surface watch',
             imageUrl: 'https://picsum.photos/id/87/200/300',
             price: 460 },
           { id: 88,
             name: 'Satin loom watch',
             imageUrl: 'https://picsum.photos/id/88/200/300',
             price: 545 },
           { id: 89,
             name: 'Linen weave watch',
             imageUrl: 'https://picsum.photos/id/89/200/300',
             price: 480 },
           { id: 90,
             name: 'Flannel sateen watch',
             imageUrl: 'https://picsum.photos/id/90/200/300',
             price: 564 } ] } },
  womens:
   { shoes:
      { id: 'women-shoes',
        title: 'Shoes',
        items:
         [ { id: 91,
             name: 'Thread loom shoe',
             imageUrl: 'https://picsum.photos/id/91/200/300',
             price: 579 },
           { id: 92,
             name: 'Crinoline sateen shoe',
             imageUrl: 'https://picsum.photos/id/92/200/300',
             price: 516 },
           { id: 93,
             name: 'Flannel mohair shoe',
             imageUrl: 'https://picsum.photos/id/93/200/300',
             price: 548 },
           { id: 94,
             name: 'Damask yarn shoe',
             imageUrl: 'https://picsum.photos/id/94/200/300',
             price: 556 },
           { id: 95,
             name: 'Damask nylon shoe',
             imageUrl: 'https://picsum.photos/id/95/200/300',
             price: 480 },
           { id: 96,
             name: 'Damask fleck shoe',
             imageUrl: 'https://picsum.photos/id/96/200/300',
             price: 458 },
           { id: 97,
             name: 'Fabric chiffon shoe',
             imageUrl: 'https://picsum.photos/id/97/200/300',
             price: 466 },
           { id: 98,
             name: 'Cotton glossy shoe',
             imageUrl: 'https://picsum.photos/id/98/200/300',
             price: 524 },
           { id: 99,
             name: 'Batiste jacquard shoe',
             imageUrl: 'https://picsum.photos/id/99/200/300',
             price: 579 },
           { id: 100,
             name: 'Batiste sateen shoe',
             imageUrl: 'https://picsum.photos/id/100/200/300',
             price: 503 } ] },
     socks:
      { id: 'women-socks',
        title: 'Socks',
        items:
         [ { id: 101,
             name: 'Corduroy nylon sock',
             imageUrl: 'https://picsum.photos/id/101/200/300',
             price: 477 },
           { id: 102,
             name: 'Batiste velvet sock',
             imageUrl: 'https://picsum.photos/id/102/200/300',
             price: 545 },
           { id: 103,
             name: 'Crinoline moleskin sock',
             imageUrl: 'https://picsum.photos/id/103/200/300',
             price: 466 },
           { id: 104,
             name: 'Corduroy loom sock',
             imageUrl: 'https://picsum.photos/id/104/200/300',
             price: 509 },
           { id: 105,
             name: 'Wool velvet sock',
             imageUrl: 'https://picsum.photos/id/105/200/300',
             price: 579 },
           { id: 106,
             name: 'Crinoline lace sock',
             imageUrl: 'https://picsum.photos/id/106/200/300',
             price: 505 },
           { id: 107,
             name: 'Flannel organza sock',
             imageUrl: 'https://picsum.photos/id/107/200/300',
             price: 425 },
           { id: 108,
             name: 'Fabric moleskin sock',
             imageUrl: 'https://picsum.photos/id/108/200/300',
             price: 457 },
           { id: 109,
             name: 'Baft chiffon sock',
             imageUrl: 'https://picsum.photos/id/109/200/300',
             price: 453 },
           { id: 110,
             name: 'Dungarees velvet sock',
             imageUrl: 'https://picsum.photos/id/110/200/300',
             price: 559 } ] },
     jeans:
      { id: 'women-jeans',
        title: 'Jeans',
        items:
         [ { id: 111,
             name: 'Angora sateen jean',
             imageUrl: 'https://picsum.photos/id/111/200/300',
             price: 444 },
           { id: 112,
             name: 'Wool weave jean',
             imageUrl: 'https://picsum.photos/id/112/200/300',
             price: 452 },
           { id: 113,
             name: 'Corduroy nylon jean',
             imageUrl: 'https://picsum.photos/id/113/200/300',
             price: 598 },
           { id: 114,
             name: 'Baft short jean',
             imageUrl: 'https://picsum.photos/id/114/200/300',
             price: 555 },
           { id: 115,
             name: 'Cotton rubber jean',
             imageUrl: 'https://picsum.photos/id/115/200/300',
             price: 566 },
           { id: 116,
             name: 'Thread yarn jean',
             imageUrl: 'https://picsum.photos/id/116/200/300',
             price: 571 },
           { id: 117,
             name: 'Crinoline chiffon jean',
             imageUrl: 'https://picsum.photos/id/117/200/300',
             price: 429 },
           { id: 118,
             name: 'Fabric mohair jean',
             imageUrl: 'https://picsum.photos/id/118/200/300',
             price: 523 },
           { id: 119,
             name: 'Crinoline glossy jean',
             imageUrl: 'https://picsum.photos/id/119/200/300',
             price: 552 },
           { id: 120,
             name: 'Angora organza jean',
             imageUrl: 'https://picsum.photos/id/120/200/300',
             price: 497 } ] },
     trousers:
      { id: 'women-trousers',
        title: 'trousers',
        items:
         [ { id: 121,
             name: 'Satin yarn trouser',
             imageUrl: 'https://picsum.photos/id/121/200/300',
             price: 431 },
           { id: 122,
             name: 'Milled jacquard trouser',
             imageUrl: 'https://picsum.photos/id/122/200/300',
             price: 412 },
           { id: 123,
             name: 'Linen surface trouser',
             imageUrl: 'https://picsum.photos/id/123/200/300',
             price: 575 },
           { id: 124,
             name: 'Cotton moleskin trouser',
             imageUrl: 'https://picsum.photos/id/124/200/300',
             price: 529 },
           { id: 125,
             name: 'Denim glossy trouser',
             imageUrl: 'https://picsum.photos/id/125/200/300',
             price: 454 },
           { id: 126,
             name: 'Dungarees glossy trouser',
             imageUrl: 'https://picsum.photos/id/126/200/300',
             price: 549 },
           { id: 127,
             name: 'Thread mohair trouser',
             imageUrl: 'https://picsum.photos/id/127/200/300',
             price: 565 },
           { id: 128,
             name: 'Corduroy yarn trouser',
             imageUrl: 'https://picsum.photos/id/128/200/300',
             price: 597 },
           { id: 129,
             name: 'Gabardine loom trouser',
             imageUrl: 'https://picsum.photos/id/129/200/300',
             price: 442 },
           { id: 130,
             name: 'Baldachin yarn trouser',
             imageUrl: 'https://picsum.photos/id/130/200/300',
             price: 536 } ] },
     jackets:
      { id: 'women-jackets',
        title: 'Jackets',
        items:
         [ { id: 131,
             name: 'Linen nylon jacket',
             imageUrl: 'https://picsum.photos/id/131/200/300',
             price: 532 },
           { id: 132,
             name: 'Damask rubber jacket',
             imageUrl: 'https://picsum.photos/id/132/200/300',
             price: 587 },
           { id: 133,
             name: 'blue velvet jacket',
             imageUrl: 'https://picsum.photos/id/133/200/300',
             price: 565 },
           { id: 134,
             name: 'Baft stiff jacket',
             imageUrl: 'https://picsum.photos/id/134/200/300',
             price: 514 },
           { id: 135,
             name: 'Linen organza jacket',
             imageUrl: 'https://picsum.photos/id/135/200/300',
             price: 591 },
           { id: 136,
             name: 'Pattern venise jacket',
             imageUrl: 'https://picsum.photos/id/136/200/300',
             price: 527 },
           { id: 137,
             name: 'Flannel lace jacket',
             imageUrl: 'https://picsum.photos/id/137/200/300',
             price: 552 },
           { id: 138,
             name: 'blue organza jacket',
             imageUrl: 'https://picsum.photos/id/138/200/300',
             price: 443 },
           { id: 139,
             name: 'Pattern velvet jacket',
             imageUrl: 'https://picsum.photos/id/139/200/300',
             price: 449 },
           { id: 140,
             name: 'Batiste glossy jacket',
             imageUrl: 'https://picsum.photos/id/140/200/300',
             price: 594 } ] },
     hats:
      { id: 'women-hats',
        title: 'Hats',
        items:
         [ { id: 141,
             name: 'Wool weave hat',
             imageUrl: 'https://picsum.photos/id/141/200/300',
             price: 453 },
           { id: 142,
             name: 'Linen organza hat',
             imageUrl: 'https://picsum.photos/id/142/200/300',
             price: 431 },
           { id: 143,
             name: 'Cotton lace hat',
             imageUrl: 'https://picsum.photos/id/143/200/300',
             price: 484 },
           { id: 144,
             name: 'Flannel sateen hat',
             imageUrl: 'https://picsum.photos/id/144/200/300',
             price: 445 },
           { id: 145,
             name: 'Cotton velvet hat',
             imageUrl: 'https://picsum.photos/id/145/200/300',
             price: 453 },
           { id: 146,
             name: 'Dungarees glossy hat',
             imageUrl: 'https://picsum.photos/id/146/200/300',
             price: 467 },
           { id: 147,
             name: 'Wool glossy hat',
             imageUrl: 'https://picsum.photos/id/147/200/300',
             price: 425 },
           { id: 148,
             name: 'Linen organza hat',
             imageUrl: 'https://picsum.photos/id/148/200/300',
             price: 441 },
           { id: 149,
             name: 'Wool stiff hat',
             imageUrl: 'https://picsum.photos/id/149/200/300',
             price: 455 },
           { id: 150,
             name: 'Milled nylon hat',
             imageUrl: 'https://picsum.photos/id/150/200/300',
             price: 577 } ] },
     shirt:
      { id: 'women-shirt',
        title: 'Shirt',
        items:
         [ { id: 151,
             name: 'Corduroy mohair shirt',
             imageUrl: 'https://picsum.photos/id/151/200/300',
             price: 536 },
           { id: 152,
             name: 'Dungarees loom shirt',
             imageUrl: 'https://picsum.photos/id/152/200/300',
             price: 433 },
           { id: 153,
             name: 'Baft yarn shirt',
             imageUrl: 'https://picsum.photos/id/153/200/300',
             price: 549 },
           { id: 154,
             name: 'Batiste venise shirt',
             imageUrl: 'https://picsum.photos/id/154/200/300',
             price: 580 },
           { id: 155,
             name: 'Pattern glossy shirt',
             imageUrl: 'https://picsum.photos/id/155/200/300',
             price: 403 },
           { id: 156,
             name: 'Thread stiff shirt',
             imageUrl: 'https://picsum.photos/id/156/200/300',
             price: 464 },
           { id: 157,
             name: 'Milled jacquard shirt',
             imageUrl: 'https://picsum.photos/id/157/200/300',
             price: 479 },
           { id: 158,
             name: 'Baldachin glossy shirt',
             imageUrl: 'https://picsum.photos/id/158/200/300',
             price: 433 },
           { id: 159,
             name: 'Baft glossy shirt',
             imageUrl: 'https://picsum.photos/id/159/200/300',
             price: 537 },
           { id: 160,
             name: 'Cotton yarn shirt',
             imageUrl: 'https://picsum.photos/id/160/200/300',
             price: 434 } ] },
     tshirt:
      { id: 'women-tshirt',
        title: 'T-shirt',
        items:
         [ { id: 161,
             name: 'blue chiffon t-shirt',
             imageUrl: 'https://picsum.photos/id/161/200/300',
             price: 564 },
           { id: 162,
             name: 'Pattern tweed t-shirt',
             imageUrl: 'https://picsum.photos/id/162/200/300',
             price: 558 },
           { id: 163,
             name: 'Baldachin venise t-shirt',
             imageUrl: 'https://picsum.photos/id/163/200/300',
             price: 585 },
           { id: 164,
             name: 'Baft weave t-shirt',
             imageUrl: 'https://picsum.photos/id/164/200/300',
             price: 455 },
           { id: 165,
             name: 'blue rubber t-shirt',
             imageUrl: 'https://picsum.photos/id/165/200/300',
             price: 428 },
           { id: 166,
             name: 'Angora short t-shirt',
             imageUrl: 'https://picsum.photos/id/166/200/300',
             price: 482 },
           { id: 167,
             name: 'blue mohair t-shirt',
             imageUrl: 'https://picsum.photos/id/167/200/300',
             price: 478 },
           { id: 168,
             name: 'Corduroy weave t-shirt',
             imageUrl: 'https://picsum.photos/id/168/200/300',
             price: 569 },
           { id: 169,
             name: 'Damask yarn t-shirt',
             imageUrl: 'https://picsum.photos/id/169/200/300',
             price: 456 },
           { id: 170,
             name: 'blue rubber t-shirt',
             imageUrl: 'https://picsum.photos/id/170/200/300',
             price: 501 } ] },
     watches:
      { id: 'women-watches',
        title: 'watches',
        items:
         [ { id: 171,
             name: 'Corduroy fleck watch',
             imageUrl: 'https://picsum.photos/id/171/200/300',
             price: 480 },
           { id: 172,
             name: 'Thread jacquard watch',
             imageUrl: 'https://picsum.photos/id/172/200/300',
             price: 506 },
           { id: 173,
             name: 'Crinoline velvet watch',
             imageUrl: 'https://picsum.photos/id/173/200/300',
             price: 522 },
           { id: 174,
             name: 'Denim velvet watch',
             imageUrl: 'https://picsum.photos/id/174/200/300',
             price: 551 },
           { id: 175,
             name: 'Linen surface watch',
             imageUrl: 'https://picsum.photos/id/175/200/300',
             price: 553 },
           { id: 176,
             name: 'Dungarees yarn watch',
             imageUrl: 'https://picsum.photos/id/176/200/300',
             price: 584 },
           { id: 177,
             name: 'Crinoline fleck watch',
             imageUrl: 'https://picsum.photos/id/177/200/300',
             price: 562 },
           { id: 178,
             name: 'Batiste rubber watch',
             imageUrl: 'https://picsum.photos/id/178/200/300',
             price: 440 },
           { id: 179,
             name: 'Dungarees moleskin watch',
             imageUrl: 'https://picsum.photos/id/179/200/300',
             price: 594 },
           { id: 180,
             name: 'Corduroy rubber watch',
             imageUrl: 'https://picsum.photos/id/180/200/300',
             price: 423 } ] } } }
export default SHOP_DATA