// Action-Types
// ============
const userActionTypes = {
  // google Signin
  SET_CURRENT_USER_USING_GOOGLE_START: "SET_CURRENT_USER_USING_GOOGLE_START",
  SET_CURRENT_USER_USING_GOOGLE_SUCCESS:
    "SET_CURRENT_USER_USING_GOOGLE_SUCCESS",
  SET_CURRENT_USER_USING_GOOGLE_FAILURE:
    "SET_CURRENT_USER_USING_GOOGLE_FAILURE",
  // email and password Signin
  SET_CURRENT_USER_USING_LOCAL_START: "SET_CURRENT_USER_USING_LOCAL_START",
  SET_CURRENT_USER_USING_LOCAL_SUCCESS: "SET_CURRENT_USER_USING_LOCAL_SUCCESS",
  SET_CURRENT_USER_USING_LOCAL_FAILURE: "SET_CURRENT_USER_USING_LOCAL_FAILURE",

  // sign up
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  // check-user if already signed in using firebase
  CHECK_USER_START: "CHECK_USER_START",
  CHECK_USER_SUCCESS: "CHECK_USER_SUCCESS",
  CHECK_USER_FAILURE: "CHECK_USER_FAILURE",
  // sign out
  SIGNOUT_USER_START: "SIGNOUT_USER_START",
  SIGNOUT_USER_SUCCESS: "SIGNOUT_USER_SUCCESS",
  SIGNOUT_USER_FAILURE: "SIGNOUT_USER_FAILURE"
};

export default userActionTypes;
