// Action-Types
// ============
const userActionTypes = {
  // google Signin
  SET_CURRENT_USER_USING_GOOGLE_START: "SET_CURRENT_USER_USING_GOOGLE_START",
  SET_CURRENT_USER_USING_GOOGLE_SUCCESS:
    "SET_CURRENT_USER_USING_GOOGLE_SUCCESS",
  SET_CURRENT_USER_USING_GOOGLE_FAILURE:
    "SET_CURRENT_USER_USING_GOOGLE_FAILURE",
  // email and password Signin
  SET_CURRENT_USER_USING_LOCAL_START: "SET_CURRENT_USER_USING_LOCAL_START",
  SET_CURRENT_USER_USING_LOCAL_SUCCESS: "SET_CURRENT_USER_USING_LOCAL_SUCCESS",
  SET_CURRENT_USER_USING_LOCAL_FAILURE: "SET_CURRENT_USER_USING_LOCAL_FAILURE",

  // sign up
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE"
};

export default userActionTypes;
